name: Bug Report
description: Report a defect that may affect system behavior, continuity, or structural integrity
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This project treats continuity and structural integrity as first-class concerns.
        Bugs that affect identity, memory, or invariants are considered high priority.

  - type: dropdown
    id: affected_ring
    attributes:
      label: Affected Ring
      description: Identify the primary architectural ring impacted
      options:
        - Source Ring
        - Bridge Ring
        - Continuity Ring (Highest Sensitivity)
        - Unsure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What is happening? What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: continuity_impact
    attributes:
      label: Continuity Impact Assessment
      description: |
        Does this issue affect identity, memory persistence, mandate coherence,
        or long-horizon behavior? If unsure, explain why.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Include minimal steps, configurations, or conditions.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Logs, screenshots, or validation data.
    validations:
      required: false
