name: Documentation Change Request
description: Request a clarification or correction to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Documentation reflects governance and architectural intent.
        Changes must not misrepresent system guarantees or structure.

  - type: dropdown
    id: decision_class
    attributes:
      label: Decision Class
      description: How significant is this documentation change?
      options:
        - Class I — Non-Structural (clarity, typos, examples)
        - Class II — Structural-Adjacent (describes behavior or boundaries)
    validations:
      required: true

  - type: textarea
    id: change_description
    attributes:
      label: Proposed Change
      description: What should be changed and why?
    validations:
      required: true

  - type: textarea
    id: risk
    attributes:
      label: Risk of Misinterpretation
      description: |
        Could incorrect documentation here cause misuse,
        incorrect assumptions, or continuity risk?
    validations:
      required: false
