name: Module or Architectural Proposal
description: Propose a new module, subsystem, or architectural change
title: "[Proposal]: "
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Proposals are evaluated conservatively.
        Structural clarity and continuity preservation take precedence over features.

  - type: dropdown
    id: affected_ring
    attributes:
      label: Primary Ring Affected
      options:
        - Source Ring
        - Bridge Ring
        - Continuity Ring (Highest Sensitivity)
    validations:
      required: true

  - type: dropdown
    id: decision_class
    attributes:
      label: Decision Class
      options:
        - Class II — Structural-Adjacent
        - Class III — Structural (Highest Sensitivity)
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal Description
      description: What are you proposing to add or change?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? Why is it necessary?
    validations:
      required: true

  - type: textarea
    id: risk_analysis
    attributes:
      label: Risk Analysis
      description: |
        Identify potential drift vectors, invariant risks,
        or cross-ring contamination concerns.
    validations:
      required: true
